# This is a basic workflow to help you get started with Actions

name: Ubuntu VM

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Installing Chrome Remote Desktop
        run: |
             wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
             dpkg --install chrome-remote-desktop_current_amd64.deb
             apt install --assume-yes --fix-broken
      - name: Installing Desktop Environment
        run: |
             export DEBIAN_FRONTEND=noninteractive
             apt install --assume-yes xfce4 desktop-base xfce4-terminal
             bash -c 'echo \"exec /etc/X11/Xsession /usr/bin/xfce4-session\" > /etc/chrome-remote-desktop-session'
             apt remove --assume-yes gnome-terminal
             apt install --assume-yes xscreensaver
             systemctl disable lightdm.service
      - name: Installing Google Chrome
        run: |
             wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
             dpkg --install google-chrome-stable_current_amd64.deb
             apt install --assume-yes --fix-broken
      - name: Final Step
        run: |
             DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AdQt8qiWgnJDEZG5ZG46kl2GBohq3u65vVuA5Xvn8dYJ4Xiia4T3IOROLTG-jCRBX1OnqA" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
             service chrome-remote-desktop start
             sleep 360
