# This is a basic workflow to help you get started with Actions

name: Ubuntu VM

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Building VM
        run: |
             wget -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
             unzip ngrok.zip
             ./ngrok authtoken 27o5HnbI46zt7YNm1Y9MUWTdWt7_2SQBW6UHPToMgmxXSA6DX
             ./ngrok tcp --region us 3389
             sudo apt install -y xrdp
             sudo apt install xfce4 -y
             sudo apt-get install xfce4 xfce4-terminal -y
             sudo sed -i.bak '/fi/a xfce4-session \n' /etc/xrdp/startwm.sh
             sudo service xrdp start
             curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"tcp:..([^"]*).*/\1/p'
             sleep 43210
